LICENSE, README.md, backend.go, client.go, client_test.go, conn.go, data.go, example_test.go, server.go, server_test.go, smtp.go
=> Adds client

conn.go
The comparison to see if User was nil was comparing the function instead of the value. I added the call to the User function.
=> Calling User function instead of comparing User function to nil

backend.go, backendutil/transform.go, conn.go, server.go, server_test.go
Will be honest: Didn't checked if it works correctly. But change seems to be pretty trivial so....
Closes #15.
=> Pass connection information to backend

client.go
This allows clients to just call Client.StartTLS(nil) to use the default server
name.
=> Populate tls.Config.ServerName if empty in StartTLS

conn.go, server.go, server_test.go
I decided to add the handler at the command level to make sure we can send a meaningful response to the connected client before dropping the connection.
Closes #50.
=> Panic handler

server.go
fixed "use of closed network connection"
ListenAndServe() always returned an error when a Close() was called.
Since the returned error value is mostly calling a panic it prevents a clean shutdown.
=> Graceful shutdown by calling Close()

conn.go
```
C: EHLO l
S: 500 5.5.1 This is a LMTP server, use LHLO
S: 250-Hello l
S: 250-PIPELINING
S: 250-8BITMIME
S: 250-ENHANCEDSTATUSCODES
S: 250-SMTPUTF8
S: 250 SIZE 33554432
```
=> server: Slightly improve LMTP support

client.go, client_test.go
Intended to protect MTA implementations from malicious recipient servers.
I am not sure about the length limit value though, for Server it is
configurable via the MaxLineLength field, for Client I do not see a context
where it can be set. Or perhaps it is not really needed?
=> client: Restrict the line length for responses

server.go
Fixes the race between multiple Serve calls if multiple endpoints are to
be used.
Fixes the race if Close is quickly called in parallel with Serve (the
case for tests that involve go-smtp as a mock SMTP server)
=> server: Protect s.listeners with mutex

client.go, client_test.go
Closes #91.
Ref.: foxcpp/maddy#205
=> Add Client.LMTPData method with ability to retrieve per-recipient status

conn.go, data.go
Probably not the best solution.
Closes #98
=> Consume message body properly on size limit hit

server.go
=> Server.Close fixes & improvements

client.go, client_test.go
Closes: https://github.com/emersion/go-smtp/issues/125
=> Make TLS mandatory for SendMail

server.go
=> fix a data racing issue

server.go
=> Handle tls.Conn handshake timeout

client.go
[RFC 8314](https://www.rfc-editor.org/rfc/rfc8314) recommends that:
> Connections to Mail Submission Servers and Mail Access Servers be made using "Implicit TLS" (as defined below), in preference to connecting to the "cleartext" port and negotiating TLS using the STARTTLS command or a similar command.
go-smtp has `Dial`, `DialTLS`, and `SendMail` functions. Adding `SendMailTLS` would add implicit TLS (aka SMTPS) support in a consistent way.
This is related to #26. I have tried to put `SendMailTLS` into my code, but that is not feasible because it accesses some unexported struct fields and functions.
`SendMailTLS` is basically `SendMail`, but with `DialTLS` instead of `Dial` and without the StartTLS stuff.
=> client: SendMailTLS

server.go, server_test.go
Add a function, server.Shutdown, which will gracefully shut down the server without interrupting any active connections (like http server).
=> Add Shutdown to Server struct

README.md, backend.go
Convenience definition for backends.
Defined in https://www.rfc-editor.org/rfc/rfc4954#section-6
=> Add ErrAuthFailed

README.md
Also there hasn't been a release since `ErrAuthFailed` was added. Mind doing a tag for that?
=> Update server example to get errors from smtp

data.go, server_test.go
Hi, this should be enough for closing #243. However, since this is a small code change, I did not test anything.
=> Remove DotLF to EOFState case

client.go, client_test.go, cmd/smtp-debug-server/main.go, conn.go, server.go, server_test.go, smtp.go
This pr implements [RRVS](https://www.rfc-editor.org/rfc/rfc7293.html) for both the client and server.
=> Implement RRVS
