parse.go
fmt.Errorf function didn't pass in the arg parameter provided. Based on the context of the log statement, I believe that is the value that should be logged. Great package! We are using it at work to send through Gmail's SMTP server.
=> Added variable to the error creation

README.md, backend.go, conn.go, server.go, server_test.go
This PR implements the ideas suggested in #8:
* Allow the `AUTH *` capabilities to be disabled completely
* Allow MUAs to send emails when not logged in
The combination of these two features is ideal when running one instance of go-smtp as an MTA on port 25 with both enabled, and another instance as an MSA on port 587 with both disabled.
=> Allow go-smtp to receive anonymous emails with no option to login

conn.go, parse.go, server.go, server_test.go
There's probably more to do here. Allow out of order MAIL/RCPTs and so
forth.
Fixes #11
=> Add a LenientSMTP option.

README.md
The server example in `README.md` missed an import for `"io"`.
=> added missing import of "io" in server example

README.md
More changes to `README.md`:
`go vet` asks for comments on exported methods when run against the server code from the  `README.md`.
=> Make go vet happy with server example

conn.go, data.go
An exported smtpError struct makes it possible to have custom smtp errors codes in func Send. This is important for soft-failing (and retry later) errors.
```
func (u *User) Send(from string, to []string, r io.Reader) error {
[...]
return &smtp.SMTPError{
Code:    450
Message: "Backend didn't repond, please retry later",
}
}
```
=> export SMTPError so it can be used in Send()

example_test.go
Typo in example file used 'from' rather than the argument 'to'
=> Fix typo in example

backendutil/backendutil.go, backendutil/transform.go, backendutil/transform_test.go, server_test.go
After considering the comments in https://github.com/emersion/go-smtp/issues/22 I still think that a TransformBackend could be useful. Especially for me since it is required for my little program https://github.com/mback2k/smtp-dkim-signer.
Considering the comments in https://github.com/emersion/go-smtp/issues/22#issuecomment-475669004 I think that option 2) "Split Transform function into separate TransformFrom, TransformTo, TransformData. Pass transformed data to underlying backend instantly." makes totally sense. The mentioned aspects are:
- The underlying backend does have an ability to report errors on From/Rcpt => true
- Can't use From/To information in TransformData =>  still possible since the required state can be kept with a Session-based approach
Therefore I am proposing to …
=> Reintroduce updated backendutil.TransformBackend after 1a1363a

conn.go, server_test.go
The change was rebased with changes from #55
A FROM Adress <> is valid and used for NDR Reports / MailerDaemon mails.
=> do not abort mailfrom if FROM is <> 

conn.go
It turned out to be more useful than I initially thought.
=> Add LocalAddr to the ConnectionState struct

conn.go, lengthlimit_reader.go, server.go, server_test.go
Without this restriction, it is pretty easy to cause OOM condition on the server by sending infinite stream of characters without line breaks. See foxcpp/maddy#116.
=> server: Restrict line length to 2000 bytes

client.go, client_test.go, data.go
Was briefly mentioned in #36 but left unimplemented.
=> client: Return SMTPError for server errors

data.go
This seems to be a convention[1] for errors that can be temporary and I find it convenient to be able to type-assert on `interface{Temporary() bool}` for any error to see if it is temporary or not.
[1]: Or at least it is implemented consistently by the net package.
=> Add Temporary method to SMTPError

conn.go
Previously, only capability was removed but server was happy to accept
the command.
=> server: Reject AUTH PLAIN on plain-text connections

conn.go
`case "QUIT"` in handle calls Conn.Close which calls Session.Logout, but then
it returns and Server.handleConn also calls Conn.Close which also calls
Session.Logout. While net.Conn is okay with double-close (it is ignored second
time), it might not be a good idea to call Session.Logout twice, so I changed
Conn.Close to reset session to nil after Logout so it will not call Logout on
second Close.
=> server: Don't call Session.Logout twice on QUIT command

backend.go, backendutil/transform.go, backendutil/transform_test.go, client.go, client_test.go, conn.go, example_test.go, go.mod, server.go, server_test.go, smtp.go
I decided to go with MailExt for client instead of adding an argument to Mail
because most users probably don't care about optional arguments.
Closes #62.
Closes #67.
=> Better support for optional MAIL Arguments

backend.go, conn.go, lmtp_server_test.go, server_test.go
Main differences from #56 are mentioned in the commit message:
>A separate interface is used so backend implementation will be aware
>of LMTP usage. This also avoids clutter in simple backend
>implementations that don't support LMTP.
Though I am not confident about this. Perhaps, having an argument for the Session.Data that is set to nil for non-LMTP would work better?
>RFC 2033 (Section 4.2) says that we should send multiple status lines if
>the same address was specified multiple times. We move responsibility of
>doing this to the backend implementation and don't do any deduplication
>themselves. This allows transparent forwarding for LMTP to be
>implemented correctly.
And this PR does not mess with LMTP/TCP or contexts, of course.
=> server: Implement per-recipient status for LMTP

conn.go, parse.go, server_test.go
SMTPUTF8 and REQUIRETLS arguments are specified without the '=' sign.
Note to myself: If you think you can get away without writting tests for
something, you are terribly wrong and should suffer.
=> server: Rewrite MAIL FROM arguments handling 

conn.go
RFC 3207 Section 4.2:
>Upon completion of the TLS handshake, the SMTP protocol is reset to
>the initial state (the state in SMTP after a server issues a 220
>service ready greeting).  The server MUST discard any knowledge
>obtained from the client, ...
In particular, this caused the following malfunction in maddy:
```
< 220 mx.maddy.test ESMTP Service Ready
> EHLO localhost
...
> MAIL FROM:<testing@two.maddy.test>
* go-smtp Session is created, TLS ConnectionState is passed to Backend *
< 550 5.7.1 TLS conversation required (msg ID = 8b66d3a9)
> STARTTLS
< 220 2.0.0 Ready to start TLS
* TLS handshake happens *
> EHLO localhost
...
> MAIL FROM:<testing@two.maddy.test>
* It is still the same Session with stale empty TLS ConnectionState *
< 550 5.7.1 TLS conversation required (msg ID = …
```
=> server: Close the session on STARTTLS

backend.go, client.go, conn.go, server_test.go
This PR adds both client-side and server-side support.
Closes #95.
=> Properly handle AUTH= parameter for MAIL command

conn.go
Rationale: TLS handshake errors can reveal configuration
issues that otherwise would be invisible unless one
happens to run tcpdump at the right moment
=> server: Log TLS handshake errors

backend.go, conn.go, server.go, server_test.go, smtp.go
See #81. This issue is not closed since it also references client support.
Replaces #104 (but hey, that initial solution saves one message copy :) )
=> Server-side CHUNKING and BINARYMIME support

backendutil/transform_test.go, data.go, server_test.go
I copy-pasted net/textproto code and I am not completely sure how it works.
If you want me to improve it - I can try though :)
Closes #108.
=> Replace net/textproto DotReader with custom implementation to avoid CRLF->LF rewrite

conn.go
On Golang 1.15, when executing `go test -buildmode pie -compiler gc`, it warns
```
conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```
and fails. The reason is that the type of the placeholde in formatting isn't specified. Also, explicit conversion (`string a_number`) isn't supported any longer (https://github.com/golang/go/issues/32479)
=> fix: int64 converted to string with unclear type

conn.go, server.go, server_test.go
This pull requests makes error handling a little more consistent and fixes issue #71. Pull request #72 has been open to address this issue for a while but without much sign of life from the author. This change
- Factors the error handling into a function as suggested
- Parametrizes the error threshold and defaults it to 3 (could be configurable in the future? At least it lives in one place now)
=> Improved error handling

client.go, client_test.go
=> client: Implement command timeouts

conn.go
- `Speak up` -> `Error: bad syntax`
- `Goodnight and good luck` -> `Bye`
=> Use same smtp reply messages as Postfix

conn.go
According to [RFC 1870](https://tools.ietf.org/html/rfc1870) SIZE should always be in extension list if it is supported by the server. Just without max size. Now 
```
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250-AUTH PLAIN
250 BINARYMIME
```
Should be
```
250-Hello test
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250-AUTH PLAIN
250-BINARYMIME
250 SIZE
```
=> Add SIZE extension when MaxMessageBytes not set

conn.go, lengthlimit_reader.go
We can fix this problem https://github.com/emersion/go-smtp/issues/81#issuecomment-801659120
By add checkflag to disable limit checking on handle BDAT data
=> Disable lineLimitReader when handle BDAT data

README.md, backend.go, backendutil/transform.go, backendutil/transform_test.go, cmd/smtp-debug-server/main.go, conn.go, example_test.go, server.go, server_test.go
Closes #136.
Closes #130.
Here is the backend API change that addresses my concerns from #114 and also resolves two other issues.
=> server: Remove authentication-related session creation

backend.go, backendutil/transform.go, backendutil/transform_test.go, cmd/smtp-debug-server/main.go, conn.go, example_test.go, server_test.go
Pass a pointer instead of the struct copy.
Will require a corresponding change in https://github.com/emersion/go-smtp-proxy
=> Change smtp.MailOptions to a pointer

client.go
This PR implements the `DialWithTimeout` and `DialTLSWithTimeout` functions. They work similar to their non-timeouts one, but with 1 improvement that they will timeout after the specified time.Duration.
1 Test has been added for the `DialWithTimeout` I couldn't find any tests for the normal `DIalTLS`.
- Resolves #155
=> client: implement Dial with timeout

README.md, client.go
For cases when more control is needed than what the helper SendMail provides.
=> Create low level Client.SendMail utility function

conn.go, server.go
ErrorLog is meant for panic logging only. It should only be used
for logging server implementation bugs, not for logging client
runtime errors.
=> server: stop logging TLS handshake errors in ErrorLog

server.go, server_test.go
Hey, not sure if you'd like the test implementation (that mock listener might be a bit weird - if you feel so, would appreciate any suggestions on how it can be improved) but here is what I came up with to address #180.
Now `Serve` does not exit on non-fatal errors from `Accept`. It also logs `handleConn` errors to the `ErrorLog` - which is not a solution but should be a partial improvement for #167.
=> Improved error handling in Server.Serve

README.md, backend.go, backendutil/transform.go, backendutil/transform_test.go, cmd/smtp-debug-server/main.go, conn.go, example_test.go, server_test.go
Client's hostname is already available inside the `ConnectionState` struct:
https://github.com/emersion/go-smtp/blob/30169acc42e795e5d35ce901c8387950b103dfd9/conn.go#L238-L246
https://github.com/emersion/go-smtp/blob/30169acc42e795e5d35ce901c8387950b103dfd9/conn.go#L206-L213
=> Remove hostname argument from the NewSession method

README.md, backend.go, backendutil/transform.go, backendutil/transform_test.go, cmd/smtp-debug-server/main.go, conn.go, example_test.go, server.go, server_test.go
Here is the rough idea of how I would resolve #147.
* `*smtp.Conn` is passed to NewSession
* ConnectionState type and Conn.State is removed
* Conn.Hostname to get HELO name
* Conn.Conn to access net.Conn
* Conn.WriteResponse, Conn.ReadLine, Conn.SetSession unexported as these should not be used by backends directly
* Conn.Reject is left as is, not sure whether it should be removed/changed anyhow
* Conn.TLSConnectionState is left as is as a shortcut.
Closes #147.
=> server: Expose smtp.Conn to backends

server.go
Reading from the underlying server connection may fail because it was closed either from the client or the server side.
Currently we only handle the former case by checking for `io.EOF`. If the server terminates the connection, we get a handler error: `use of closed network connection`.
This fix is similar to the server connection handling in [go-imap.](https://github.com/emersion/go-imap/blob/master/server/conn.go#L321)
=> server: handle error after closing connection

conn.go, lmtp_server_test.go, server.go
- The excess number of recipients should be responded with `4XX`.
- Disconnections due to network errors or idle timeouts should be `4XX`.
- `3XX` codes do not have enhanced codes.
- Other typos.
---
This PR may fix #195 .
=> server: Correct status codes in several responses.

conn.go, server_test.go
I have a client that sends a message to an SMTP server using this library (the Protonmail bridge) and encounter problems because the client doesn't enclose the `AUTH=` parameter in angle brackets.
I looked at [the relevant RFC](https://datatracker.ietf.org/doc/html/rfc4954#section-5) and it doesn't appear that this parameter requires angle brackets. [RFC2821 (referenced by the other RFC) section 4.1.2](https://datatracker.ietf.org/doc/html/rfc2821#section-4.1.2) requires angle brackets for a _Path_ but not for a Mailbox. It explicitly allows Mailboxes without angle brackets:
```
Mailbox = Local-part "@" Domain
Local-part = Dot-string / Quoted-string
; MAY be case-sensitive
Dot-string = Atom *("." Atom)
Atom = 1*atext
(From https://datatracker.ietf.org/doc/html/rfc2822#section-3.2.4)
atext …
```
=> Update MAIL FROM AUTH handling to accept mailbox without angle brackets

README.md
- Add `*smtp.RcptOptions` in session method `Rcpt()`.
=> Fix sample server for v0.18.0.

client_test.go, conn.go
With this method call:
```go
email := "e=mc2@example.com"
c.Mail(email, &MailOptions{Auth: &email})
```
this should be sent to the server:
```
MAIL FROM:<e=mc2@example.com> AUTH=e+3Dmc2@example.com
```
However, following thing is sent:
```
MAIL FROM:<e=mc2@example.com> AUTH=e+65+3D=+3Dm+6Dc+632+32@+40e+65x+78a+61m+6Dp+70l+6Ce+65.+2Ec+63o+6Fm+6D
```
This PR will fix it.
=> Fix broken encodeXtext()

server.go
*   [RFC2033](https://datatracker.ietf.org/doc/rfc2033/) does _not_ state that "LMTP mode cannot be used with a TCP listener": It states that it "_MUST NOT be used on the TCP **service port 25**_".  In fact, most LMTP implementations support TCP, and the default port number is often 24.
*   There is at least one implementation that supports SMTP over UNIX domain socket: [OpenSMTPD](https://man.openbsd.org/smtpd.conf.5).
*    TLS over UNIX domain socket seems worthwhile. On some systems, since permissions of pathname socket  are ignored, they cannot be relied upon (See [unix(7)](https://man7.org/linux/man-pages/man7/unix.7.html)).
That's why this PR makes changes to allow both SMTP and LMTP servers to be used on either TCP or UNIX domain socket with optional TLS.
---
Some other changes:
* …
=> Both SMTP and LMTP servers may listen either TCP or UNIX domain socket

client.go, client_test.go
This makes it so NewClient never blocks, much like tls.Client.
This allows callers to have better control over timeouts.
=> client: delay greeting

conn.go
Conn.Hostname is the only way hostname can be read in NewSession. https://github.com/emersion/go-smtp/commit/d62ec8c7d00892343e81b21ad4fb33bcb7a900bb breaks this by setting it _after_ NewSession.
=> Fix Conn.Hostname being empty when NewSession is called

data.go, server_test.go
Note that this case is not exactly "no mail data" case referenced in RFC 5321. It is a message containing two empty lines (not one). FWIW This is what go-smtp client send if data writer is closed without writing to it - not sure where extra CRLF comes from.
=> Parse DATA\r\n\r\n.\r\n as \r\n\r\n message

conn.go, server_test.go
Currently,
```code
MAIL FROM:<alice@wonderland.book> BODY=8bitMIME
```
is responded by `500 5.5.4 Unknown BODY value`.
This PR fixes it to make the parameter value case-insensitive.
___
In this occasion, it also makes status code for invalid parameter value `501` as RFC describes.
=> Server: The value of BODY parameter is case-insensitive

backend.go, conn.go, server.go
Closes: https://github.com/emersion/go-smtp/issues/170
Future work:
- Drop `Session.AuthPlain`
- Drop `Server.AuthDisabled`
=> server: replace EnableAuth with AuthSession

client.go, conn.go
With anonymous authentication according to RFC4505 the trace information string is optional, and SMTP authentication extension described in RFC4954 states that:
If the client is transmitting an initial response of zero
length, it MUST instead transmit the response as a single
equals sign ("=").  This indicates that the response is
present, but contains no data.
Fixes #258
=> Fix anonymous authentication with empty trace information string

server.go
When an incoming connection is not working, e.g. due to a missing proxy protocol header, there is currently no chance to catch details on server side, e.g. to debug where it came from.
This PR adds the remote address to the log line, making it more consistent with other logs like `panic serving %v: %s...`
Another solution might be to pass the connection as first parameter to the logger interface functions, but it's a heavier change and it might not work for situations where the connection could not be established at all.
=> Add remote addr in error handler log

client.go, client_test.go
Resolves https://github.com/emersion/go-smtp/issues/245
Also fixes possible problem with sending only `elho` after `StartTLS` ignoring `helo`
=> Allow manual Hello after StartTLS

client.go, conn.go
Resolves [EHLO after RSET #269](https://github.com/emersion/go-smtp/issues/269)
=> Allow custom EHLO after RSET again

example_server_test.go
This was originally added to the `README.md` in #222, but was lost when the examples were removed from there.
Re-add it so that it's clearer that this library doesn't enforce authentication by default.
=> Add checking for auth to Server example.

conn.go
This very simple pr allows multi line error messages delimited with \n, per Issue #275.
=> server: handle newline characters in error messages

client.go, client_test.go
Closes: https://github.com/emersion/go-smtp/issues/189
=> client: introduce DataCommand
